const ROOT_PRODUCT = document.getElementById('product')
const ROOT_HEADER = document.getElementById('header')
const ROOT_SHOPPING = document.getElementById('shopping')
const ROOT_SPINNER = document.getElementById('spinner')
const ROOT_ERRORPG = document.getElementById('errorPg')